version: '3.8'

services:
  # Spring Boot 애플리케이션 서비스
  app:
    build: .
    container_name: consumption-analyzer-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/consumption_analyzer
      - SPRING_DATASOURCE_USERNAME=your_db_user
      - SPRING_DATASOURCE_PASSWORD=your_db_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy: # <--- GPU 설정 추가
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:14
    container_name: consumption-analyzer-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=consumption_analyzer
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user -d consumption_analyzer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: